module.exports = {
    env: process.env.NODE_ENV || 'development', //ETL - 'sandbox', dev - 'development', prod - 'production'
    port: process.env.PORT || 3000,
    trustProxy: process.env.TRUST_PROXY || 'no',
    secureMode: process.env.SECURE_MODE || false,
    secret: process.env.SECRET || 'lakikihdgdfdjjjdgd67264664vdjhjdyncmxuei8336%%^#%gdvdhj????jjhdghduue',
    sysMongoURL: process.env.SYS_MONGOLAB_URL || 'mongodb://localhost:27017/milk-test',
    logMongoURL: process.env.LOG_MONGOLAB_URL || 'mongodb://localhost:27017/milk-log',
    etlMongoURL: process.env.ETL_MONGOLAB_URL || 'mongodb://localhost:27017/milk-etl',
    arcMongoURL: process.env.ARC_MONGOLAB_URL || 'mongodb://localhost:27017/milk-arc',
    noFrontendCaching: process.env.NO_CACHE || 'yes',
    frontendCacheExpiry: process.env.FRONTEND_CACHE_EXPIRY || '90',
    backendCacheExpiry: process.env.BACKEND_CACHE_EXPIRY || '90',
    rateLimit: process.env.RATE_LIMIT || '1800',
    rateLimitExpiry: process.env.RATE_LIMIT_EXPIRY || '3600000',
    redisURL: process.env.REDIS_URL || 'redis://127.0.0.1:6379/1',
    letsencryptSSLVerificationURL: process.env.LETSENCRYPT_VERIFICATION_URL || '/.well-known/acme-challenge/xvArhQBSilF4V30dGUagNAZ96ASipB0b0ex0kXn0za8',
    letsencryptSSLVerificationBody: process.env.LETSENCRYPT_VERIFICATION_BODY || 'xvArhQBSilF4V30dGUagNAZ96ASipB0b0ex0kXn0za8._v6aFbaRYWeOmSebtlD-X4Ixf5tPsyULMsXM8HjsK-Q',
    maxContentLength: process.env.MAX_CONTENT_LENGTH || '99999999',
    enforceSSL: process.env.ENFORCE_SSL || 'no',
    queueUIUsername: process.env.QUEUE_UI_USERNAME || 'admin',
    queueUIPassword: process.env.QUEUE_UI_PASSWORD || 'password123/',
    queueUIPort: process.env.QUEUE_UI_PORT || 8080,
    apiDBKey: process.env.API_DB_Key || 'MDg4NWM1NTA0ZTZlNTQ5MjAzNzA1ODBlOWVkNzI3MzdlNmYxZTcyMjVkOTA3N2JjYTBhZjA0YmM0N2U4NDZkNi8vLy8vLzQ1MDY=',
    timezone: process.env.TIMEZONE || '+05:30',
    clockTimezone: process.env.CLOCK_TIMEZONE || 'Asia/India',
    workerConcurrency: process.env.WORKER_CONCURRENCY || '1',
    logglyToken: process.env.LOGGLY_TOKEN || false,
    logglySubdomain: process.env.LOGGLY_SUBDOMAIN || false,
    logglyTag: process.env.LOGGLY_TAG || false,
    logTo: process.env.LOG_TO || 'File',
    jwtKey: process.env.JWT_KEY || 'parcelgurusecret',
    jwtExpireIn: process.env.JWT_EXPIREIN || 30, //mins
    otpExpireIn: process.env.OTP_EXPIREIN || 5, //mins
    passwordStrength: process.env.PASSWORD_STRENGTH || '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})',
    payMerchantKey: process.env.MerchantKey || "HFykJRx6",
    payMerchantSalt: process.env.MerchantSalt || "Rt58RBRpXE",
    payAuthHeader: process.env.AuthHeader || "IGq3ukhILDENKCSP3NJQ3PUNas4I38cNKfzblG+snoI=",
    payFurl: process.env.Furl || "http://localhost:3000/api/v1/payment/failure/",
    paySurl: process.env.Surl || "http://localhost:3000/api/v1/payment/success/",
    failureRedirect: process.env.failureRedirect || "http://localhost:4200/orderFailure?orderId=",
    successRedirect: process.env.successRedirect || "http://localhost:4200/orderSuccess?orderId=",
    smtpHost: process.env.smtpHost || "smtp.ethereal.email",
    smtpPort: process.env.smtpPort || 587,
    smtpUser: process.env.smtpUser || "joannie.boyer@ethereal.email",
    smtpPass: process.env.smtpPass || "FNTnq857xYGvpYCudC",
    smtpUri: process.env.smtpUri || "http://localhost:4200/Agencylogin/",
    smtpNoreply: process.env.smtpNoreply || "no-reply@myparcelguru.com",
    paginateLimit: process.env.paginateLimit || 10
}